"""Injectable provider contracts owned by PK-210."""
from __future__ import annotations

from typing import Protocol

from .models import (
    AudioResult,
    EncodedUtterance,
    ProviderCapabilities,
    ProviderHealth,
    SynthesisRequest,
    Transcript,
    TranscriptionRequest,
    VoicePackRef,
    UtteranceEncodingRequest,
)


class SpeechToTextProvider(Protocol):
    async def health(self) -> ProviderHealth: ...
    def capabilities(self) -> ProviderCapabilities: ...
    async def transcribe(self, request: TranscriptionRequest) -> Transcript: ...
    async def cancel(self, request_id: str) -> None: ...
    async def close(self) -> None: ...


class ConversationReply(Protocol):
    text: str
    emotion: str
    timestamp: str


class ConversationProvider(Protocol):
    async def health(self) -> ProviderHealth: ...
    def capabilities(self) -> ProviderCapabilities: ...
    async def chat(self, message: str, *, request_id: str) -> ConversationReply: ...
    async def cancel(self, request_id: str) -> None: ...
    async def close(self) -> None: ...


class TextToSpeechProvider(Protocol):
    async def health(self) -> ProviderHealth: ...
    def capabilities(self) -> ProviderCapabilities: ...
    async def synthesize(self, request: SynthesisRequest, voice_pack: VoicePackRef) -> AudioResult: ...
    async def cancel(self, request_id: str) -> None: ...
    async def close(self) -> None: ...


class UtteranceEncoder(Protocol):
    async def health(self) -> ProviderHealth: ...
    def capabilities(self) -> ProviderCapabilities: ...
    async def encode(self, request: UtteranceEncodingRequest) -> EncodedUtterance: ...
    async def cancel(self, request_id: str) -> None: ...
    async def close(self) -> None: ...


class VoicePackResolver(Protocol):
    async def health(self) -> ProviderHealth: ...
    def capabilities(self) -> ProviderCapabilities: ...
    async def resolve_active_pack(self) -> VoicePackRef: ...
    async def resolve_pack(self, pack_id: str) -> VoicePackRef: ...
    async def cancel(self, request_id: str) -> None: ...
    async def close(self) -> None: ...
