"""Compatibility exports for the modular calendar implementation."""

from features.calendar.models import CalendarEvent
from features.calendar.repository import (
    CalendarMemoStore,
    CalendarPersistenceError,
    CalendarRepository,
    CalendarStateError,
    DATA_DIR,
    DEFAULT_STORE,
)
from features.calendar.service import (
    MASTERY_REALMS,
    MASTERY_STAGES,
    MASTERY_TARGET_HOURS,
    WEEKDAYS,
    add_event,
    add_practice,
    events_for_day,
    get_status,
    mastery_level,
    normalize_day,
    parse_day,
    practice_message,
    reset,
    skill_overview,
    skill_status,
    today_key,
    today_message,
    today_summary,
    upcoming_events,
)

__all__ = [
    "CalendarEvent",
    "CalendarMemoStore",
    "CalendarPersistenceError",
    "CalendarRepository",
    "CalendarStateError",
    "DATA_DIR",
    "DEFAULT_STORE",
    "MASTERY_REALMS",
    "MASTERY_STAGES",
    "MASTERY_TARGET_HOURS",
    "WEEKDAYS",
    "add_event",
    "add_practice",
    "events_for_day",
    "get_status",
    "mastery_level",
    "normalize_day",
    "parse_day",
    "practice_message",
    "reset",
    "skill_overview",
    "skill_status",
    "today_key",
    "today_message",
    "today_summary",
    "upcoming_events",
]
