"""Project module boundaries overlaid with local lifecycle state."""

from copy import deepcopy
from typing import Any, Dict, Tuple

from core.modules.contracts import (
    CORE_MODULE_CONTRACTS,
    CORE_RESERVED_MODULE_IDS,
    conflicting_core_namespace,
)
from features.module_manager.service import get_module_manager


_MODULES: Tuple[Dict[str, Any], ...] = (
    {
        "key": "module_manager",
        "label": "可安装模块生命周期与加载基础",
        "task_id": "PK-010",
        "task_file": "tasks/PK-010-installable-modules.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/modules",
            "/api/v1/modules/official-catalog",
            "/api/v1/modules/official-catalog/refresh",
            "/api/v1/modules/{module_id}/install",
            "/api/v1/modules/{module_id}/install-official",
            "/api/v1/modules/{module_id}/enable",
            "/api/v1/modules/{module_id}/disable",
            "/api/v1/modules/{module_id}/update",
            "/api/v1/modules/{module_id}/update-official",
            "/api/v1/modules/{module_id}/rollback",
            "/api/v1/modules/{module_id}/rollback-official",
            "/api/v1/modules/{module_id}/configuration/check",
            "/api/v1/modules/{module_id}/purge-data",
        ],
        "target_namespace": "/api/v1/modules",
        "migration_status": "modular",
        "data_owner": "module_manager:ignored registry/runtime/module-data plus public official catalog metadata cache",
        "network_side_effects": "none for module/catalog GET; anonymous fixed official GitHub catalog only on explicit refresh and fixed Release asset only on confirmed install/update-official",
        "failure_mode": "structured catalog/download errors, last-good cache fallback, bounded trusted redirects/bytes/time, SHA-256+manifest+ModuleManager validation, and no partial registry/runtime state",
    },
    {
        "key": "catalog",
        "label": "模块目录与任务体系",
        "task_id": "PK-001",
        "task_file": "tasks/PK-001-modular-foundation.md",
        "process": "main-api",
        "current_endpoints": ["/api/v1/modules"],
        "target_namespace": "/api/v1/modules",
        "migration_status": "modular",
    },
    {
        "key": "dashboard",
        "label": "控制台公共外壳",
        "task_id": "PK-100",
        "task_file": "tasks/PK-100-dashboard-shell.md",
        "process": "main-api",
        "current_endpoints": [
            "/dashboard",
            "/dashboard/static/{asset_path}",
            "/dashboard/status",
            "/api/v1/dashboard/ui-assets",
            "/api/v1/dashboard/ui-assets/{panel_id}/avatar",
        ],
        "target_namespace": "/api/v1/dashboard",
        "migration_status": "modular",
        "data_owner": "dashboard:ignored server/data/dashboard_ui/avatars UI customization assets",
        "network_side_effects": "local UI asset list/read on page load; write/delete only on explicit avatar customization",
        "failure_mode": "invalid ID/type/signature/size/origin rejected before atomic replace; failed upload keeps current default or page preview",
    },
    {
        "key": "daily_briefing",
        "label": "每日情报与 Kei 播报",
        "task_id": "PK-110",
        "task_file": "tasks/PK-110-daily-briefing.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/briefing/today",
            "/api/v1/briefing/generation-status",
            "/api/v1/briefing/generate",
            "/api/v1/briefing/refresh",
            "/api/v1/briefing/today/script",
            "/briefing/today",
            "/briefing/today/voice",
            "/dashboard/briefing/status",
            "/dashboard/briefing/generate",
        ],
        "target_namespace": "/api/v1/briefing",
        "migration_status": "modular",
        "data_owner": "daily_briefing:server/data/briefing_cache normalized items + current-day narration",
        "network_side_effects": "collectors and PK-200 only on explicit generate/refresh/eligible missing-source patch; cache and in-memory generation-status reads are local-only",
        "failure_mode": "per-source isolation with redacted coverage; failed refresh reuses old cache and main+narration commit together with rollback; rewrite/voice return explicit fallback/degradation",
    },
    {
        "key": "intel_sources",
        "label": "每日情报来源注册表与配置",
        "task_id": "PK-115",
        "task_file": "tasks/PK-115-intel-source-registry.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/intel-sources",
            "/api/v1/intel-sources/{field}",
            "/api/v1/intel-sources/{field}/{index}",
            "/dashboard/intel-sources",
        ],
        "target_namespace": "/api/v1/intel-sources",
        "migration_status": "modular",
        "data_owner": "intel_sources:ignored server/data/intel_sources.json personal target registry",
        "network_side_effects": "none; registry reads/writes never collect or refresh briefing data",
        "failure_mode": "invalid writes are rejected before atomic replace; corrupt local state is not overwritten",
        "dashboard_surface": "legacy:/dashboard#intel-sources using versioned API",
    },
    {
        "key": "x_monitor",
        "label": "X/Nitter 用户资料与今日言论",
        "task_id": "PK-120",
        "task_file": "tasks/PK-120-x-monitor.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/x/profiles",
            "/api/v1/x/profiles/resolve",
            "/api/v1/x/posts",
            "/api/v1/x/posts/fetch",
            "/api/v1/x/posts/query",
            "/dashboard/intel-sources/x-profiles/resolve",
            "/dashboard/intel-sources/x-posts",
            "/dashboard/intel-sources/x-posts/fetch",
        ],
        "target_namespace": "/api/v1/x",
        "migration_status": "modular",
        "data_owner": "x_monitor:ignored x_profiles.json + x_daily_posts.json; target lists belong to intel_sources",
        "network_side_effects": "Nitter only on explicit profile resolve, per-user today fetch, bounded day/since query, or briefing collection; cache reads, date selection, result switching, and UI folding are offline",
        "failure_mode": "per-user isolation, atomic cache replacement, six-hour profile/collector cooldown, and redacted errors",
        "dashboard_surface": "legacy:/dashboard#intel-sources using versioned API",
    },
    {
        "key": "bilibili",
        "label": "B 站资料与动态采集",
        "task_id": "PK-130",
        "task_file": "tasks/PK-130-bilibili.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/bilibili/profiles",
            "/api/v1/bilibili/profiles/resolve",
            "/api/v1/bilibili/credentials/status",
            "/api/v1/bilibili/credentials",
            "/api/v1/bilibili/credentials/validate-and-collect",
            "/dashboard/intel-sources/bilibili-profiles/resolve",
            "/dashboard/intel-sources/bilibili-credentials/status",
            "/dashboard/intel-sources/bilibili-credentials",
            "/dashboard/intel-sources/bilibili-credentials/validate-and-collect",
        ],
        "target_namespace": "/api/v1/bilibili",
        "migration_status": "modular",
        "data_owner": "bilibili:ignored profiles + local active/candidate credential store; UID list belongs to intel_sources",
        "network_side_effects": "status reads and candidate saves are offline; only explicit profile refresh or validate-and-collect reaches Bilibili",
        "failure_mode": "atomic candidate promotion, bounded retry, per-UID cooldown, partial coverage and redacted upstream failures",
        "dashboard_surface": "legacy:/dashboard#intel-sources using versioned API",
    },
    {
        "key": "youtube",
        "label": "YouTube 频道采集",
        "task_id": "PK-131",
        "task_file": "tasks/PK-131-youtube.md",
        "process": "main-api",
        "current_endpoints": [],
        "target_namespace": "/api/v1/youtube",
        "migration_status": "modular",
        "data_owner": "youtube:none; Channel ID list belongs to intel_sources and results belong to daily_briefing",
        "network_side_effects": "public Atom feed only during explicit briefing collection or eligible patch",
        "failure_mode": "invalid Channel IDs make no request; feed failures remain source-local",
    },
    {
        "key": "github_intel",
        "label": "GitHub 用户与仓库采集",
        "task_id": "PK-132",
        "task_file": "tasks/PK-132-github.md",
        "process": "main-api",
        "current_endpoints": [],
        "target_namespace": "/api/v1/github-intel",
        "migration_status": "modular",
        "data_owner": "github_intel:none; targets belong to intel_sources and optional token stays environment-only",
        "network_side_effects": "GitHub public API only during explicit briefing collection or eligible patch",
        "failure_mode": "per-target isolation, bounded pagination, rate-limit retry_after and redacted errors",
    },
    {
        "key": "papers",
        "label": "论文来源与作者追踪",
        "task_id": "PK-133",
        "task_file": "tasks/PK-133-papers.md",
        "process": "main-api",
        "current_endpoints": [],
        "target_namespace": "/api/v1/papers",
        "migration_status": "modular",
        "data_owner": "papers:ignored arXiv cache; author lists belong to intel_sources and API key stays environment-only",
        "network_side_effects": "arXiv/Crossref/Semantic Scholar only during explicit briefing collection or eligible patch",
        "failure_mode": "three independent source results with fallback-only Semantic queries and cross-source deduplication",
    },
    {
        "key": "rss_intel",
        "label": "RSS 与信息差来源",
        "task_id": "PK-134",
        "task_file": "tasks/PK-134-rss.md",
        "process": "main-api",
        "current_endpoints": [],
        "target_namespace": "/api/v1/rss-intel",
        "migration_status": "modular",
        "data_owner": "rss_intel:none; application-owned feed rules remain in intel_config",
        "network_side_effects": "fixed HTTPS public feeds only during explicit briefing collection or eligible patch",
        "failure_mode": "closed feed allowlist, bounded redirects/body, partial coverage and redacted errors",
    },
    {
        "key": "qq_bridge",
        "label": "QQ bridge 与定时推送",
        "task_id": "PK-140",
        "task_file": "tasks/PK-140-qq-bridge.md",
        "process": "sidecar:qq-bridge",
        "current_endpoints": [
            "/api/v1/qq-control/status",
            "/api/v1/qq-control/start",
            "/api/v1/qq-control/stop",
            "/api/v1/qq-control/schedules/daily-briefing",
            "/api/v1/qq-control/schedules/life-support",
            "/dashboard/qq-bridge/status",
            "/dashboard/qq-bridge/start",
            "/dashboard/briefing/schedule",
            "/dashboard/life-support/schedule",
            "/api/v1/conversation",
            "/api/v1/briefing/generate",
            "/api/v1/briefing/today",
            "/api/v1/demon-slayer/status",
            "/api/v1/demon-slayer/goals",
            "/api/v1/demon-slayer/checkins",
            "/api/v1/demon-slayer/reviews/daily",
            "/api/v1/fitness/status",
            "/api/v1/fitness/checkins",
            "/api/v1/focus/status",
            "/api/v1/focus/start",
            "/api/v1/focus/stop",
            "/api/v1/focus/encouragement",
            "/api/v1/calendar/today",
            "/api/v1/calendar/status",
            "/api/v1/calendar/events",
            "/api/v1/calendar/practice",
            "/life-support/reminder",
        ],
        "target_namespace": "/api/v1/qq-control",
        "migration_status": "modular",
        "data_owner": "qq_control owns two local schedule files; the Node sidecar owns bounded hashed briefing/life/focus-encouragement delivery markers plus ephemeral bounded user-bound goal-ID and pending-goal-confirmation caches; pending goal titles are memory-only and expire after 10 minutes; focus encouragement state stores only user hashes plus opaque session/timestamps/status; QQ credentials remain only in the ignored bridge .env; business repositories and personal state remain owned by their main-API modules",
        "network_side_effects": "Gateway/token/C2C send only in the explicit Node sidecar; fixed versioned local HTTP calls cover conversation, business-menu reads/explicit writes, briefing generation/cache, confirmed recurring demon-goal creation, demon check-in optional controlled encouragement, focus active-session validation/one controlled generation call and the controlled reminder seam; no arbitrary URL/prompt, legacy fallback or direct business-file access",
        "failure_mode": "fail-closed allowlist/corrupt scheduler or focus state, ACK-before-business dispatch, bounded keyboard/output/goal IDs, user-bound single-use expiring goal confirmation, fixed timeout/404/409/422/500 prompts, bounded reconnect/token retry, per-user at-most-once delivery, deterministic reminder/focus fallback, and launcher readiness without auto-install",
    },
    {
        "key": "demon_slayer",
        "label": "斩妖除魔",
        "task_id": "PK-150",
        "task_file": "tasks/PK-150-demon-slayer.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/demon-slayer/status",
            "/api/v1/demon-slayer/goals",
            "/api/v1/demon-slayer/goals/{goal_id}",
            "/api/v1/demon-slayer/checkins",
            "/api/v1/demon-slayer/reviews/{period}",
            "/api/v1/demon-slayer/rewards",
            "/api/v1/demon-slayer/rewards/{reward_id}/redeem",
            "/demon/status",
            "/demon/plan",
            "/demon/goals/{goal_id}",
            "/demon/checkin",
            "/demon/reminder",
            "/demon/review/{period}",
            "/demon/wish",
            "/demon/redeem",
            "/demon/reset",
        ],
        "target_namespace": "/api/v1/demon-slayer",
        "migration_status": "modular",
        "data_owner": "demon_slayer:existing personal state at server/systems/data/demon_slayer.json; goals, activation intervals, check-ins, points, rewards, redemptions and review bonuses; cadence streak fields are service-derived",
        "network_side_effects": "PK-200 controlled text generation only on explicit review or a non-duplicate completed check-in with with_encouragement=true; status and other writes are local-only",
        "failure_mode": "corrupt state or lifecycle fails closed; writes use locked unique-temp atomic replacement; status/check-in statistics are deterministic and review/check-in encouragement generation falls back deterministically",
        "dashboard_surface": "legacy:/dashboard#demon using versioned API; no business state in localStorage",
    },
    {
        "key": "affection_memory",
        "label": "好感度与长期记忆",
        "task_id": "PK-160",
        "task_file": "tasks/PK-160-affection-memory.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/relationship/status",
            "/api/v1/relationship/events",
            "/api/v1/relationship/choices",
            "/api/v1/memories",
            "/api/v1/memories/{memory_id}",
            "/affection/status",
            "/affection/event",
            "/affection/choose",
            "/affection/reset",
            "/memories",
            "/memories/{memory_id}",
            "/memories/clear",
        ],
        "target_namespace": "/api/v1/relationship",
        "migration_status": "modular",
        "data_owner": "affection_memory:separate existing personal files server/data/affection_state.json and server/data/memories.json; no automatic migration",
        "network_side_effects": "local-client and trusted-dashboard-Origin only; local state except optional local TTS on explicit choice; PK-200 consumes bounded read-only context text",
        "failure_mode": "cross-site reads/writes/preflight fail before wildcard CORS; legacy frozen active events are normalized read-only; corrupt/tampered state fails closed; atomic replacement preserves old bytes",
        "dashboard_surface": "legacy:/dashboard#affection+#memories using versioned APIs; no personal state in localStorage",
    },
    {
        "key": "fitness",
        "label": "健身打卡",
        "task_id": "PK-170",
        "task_file": "tasks/PK-170-fitness.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/fitness/status",
            "/api/v1/fitness/checkins",
            "/fitness/status",
            "/fitness/checkin",
            "/fitness/reset",
        ],
        "target_namespace": "/api/v1/fitness",
        "migration_status": "modular",
        "data_owner": "fitness:existing personal state server/data/fitness_checkins.json; no alternate production store or automatic migration",
        "network_side_effects": "local-client and trusted-dashboard-Origin only; GET and versioned check-in have no network/TTS side effects; legacy reward audio is explicit",
        "failure_mode": "cross-site and remote access fails before repository; invalid structure fails closed; locked atomic replacement preserves old bytes",
        "dashboard_surface": "legacy:/dashboard#fitness using versioned API; no fitness state in localStorage",
    },
    {
        "key": "focus",
        "label": "专注计时",
        "task_id": "PK-180",
        "task_file": "tasks/PK-180-focus.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/focus/status",
            "/api/v1/focus/start",
            "/api/v1/focus/stop",
            "/api/v1/focus/reset",
            "/api/v1/focus/encouragement",
            "/focus/status",
            "/focus/start",
            "/focus/stop",
            "/focus/reset",
        ],
        "target_namespace": "/api/v1/focus",
        "migration_status": "installable",
        "data_owner": "focus:existing personal state at server/systems/data/focus_timer.json; session IDs and timer facts; no QQ identity or delivery state",
        "network_side_effects": "local-only controlled PK-200 generation on explicit due encouragement after active session identity revalidation; status/start/stop/reset stay local and encouragement never writes conversation history",
        "failure_mode": "corrupt focus state fails closed without overwrite; inactive/mismatched session returns fixed 409 before generation; generator failures return generated=false for sidecar fallback",
    },
    {
        "key": "calendar",
        "label": "日历备忘与修炼记录",
        "task_id": "PK-190",
        "task_file": "tasks/PK-190-calendar.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/calendar/today",
            "/api/v1/calendar/status",
            "/api/v1/calendar/events",
            "/api/v1/calendar/practice",
            "/api/v1/calendar/reset",
            "/calendar/today",
            "/calendar/status",
            "/calendar/event",
            "/calendar/practice",
            "/calendar/reset",
        ],
        "target_namespace": "/api/v1/calendar",
        "migration_status": "modular",
        "data_owner": "calendar:server/systems/data/calendar_memo.json",
        "dashboard_surface": "legacy:/dashboard#calendar",
    },
    {
        "key": "conversation",
        "label": "LLM 对话与模型方案",
        "task_id": "PK-200",
        "task_file": "tasks/PK-200-conversation-llm.md",
        "process": "main-api",
        "current_endpoints": [
            "/api/v1/conversation",
            "/api/v1/conversation/history",
            "/api/v1/llm-profile",
            "/chat",
            "/chat/text-only",
            "/history",
            "/history/clear",
            "/ws/chat",
            "/dashboard/llm/profile",
        ],
        "target_namespace": "/api/v1/conversation",
        "migration_status": "modular",
        "data_owner": "conversation:in-memory-history+server/data/llm_profile.json",
        "dashboard_surface": "legacy:/dashboard#llm-profile",
        "secret_owner": "process-environment:LLM_API_KEY (never profile/API/browser)",
        "network_side_effects": "OpenAI-compatible chat/completions only on explicit chat/generation/profile-test",
        "failure_mode": "chat uses Kei fallback; typed generation reports generated=false; failed profile update preserves active runtime",
    },
    {
        "key": "voice",
        "label": "语音公共契约与编排",
        "task_id": "PK-210",
        "task_file": "tasks/PK-210-voice.md",
        "process": "main-api+asr+tts",
        "current_endpoints": [
            "/api/v1/voice/health",
            "/api/v1/voice/chat",
            "/api/v1/voice/chat/stream",
            "/api/v1/voice/audio/{filename}",
            "/api/v1/voice-control/status",
            "/api/v1/voice-control/asr/start",
            "/api/v1/voice-control/asr/start-background",
            "/api/v1/voice-control/asr/stop",
            "/api/v1/voice-control/gpt-sovits/start",
            "/api/v1/voice-control/gpt-sovits/start-background",
            "/api/v1/voice-control/gpt-sovits/stop",
            "/voice/health",
            "/voice/chat",
            "/voice/chat/stream",
            "/voice/audio/{filename}",
        ],
        "target_namespace": "/api/v1/voice",
        "migration_status": "modular",
        "data_owner": "voice:per-request-staging+server/output/voice_replies",
        "network_side_effects": "ASR :8010 and TTS :9880 only during explicit voice calls/health",
        "failure_mode": "ASR/conversation fail closed; TTS failure returns explicit text_only degradation",
    },
    {
        "key": "gpt_sovits_engine_provider",
        "label": "GPT-SoVITS Engine Provider 与受控获取",
        "task_id": "PK-211",
        "task_file": "tasks/PK-211-gpt-sovits-engine-provider.md",
        "process": "tts-sidecar",
        "current_endpoints": [
            "http://127.0.0.1:9880/",
            "http://127.0.0.1:9880/tts",
            "http://127.0.0.1:9880/docs",
        ],
        "target_namespace": "/api/v1/voice",
        "migration_status": "modular",
        "data_owner": "external-engine:project descriptor + ignored local registration; no role assets",
        "network_side_effects": "9880 only on explicit synth/health; fixed official HTTPS only on user-invoked acquisition",
        "failure_mode": "shared engine sessions serialize switch+synthesis; failed/cancelled switches roll back or report unknown; acquisition verifies SHA-256 before atomic install",
    },
    {
        "key": "voice_pack_registry",
        "label": "Voice Pack 注册表与 Kei 模型包",
        "task_id": "PK-212",
        "task_file": "tasks/PK-212-voice-pack.md",
        "process": "main-api+tts-sidecar",
        "current_endpoints": [
            "/api/v1/voice-packs",
            "/api/v1/voice-packs/import",
            "/api/v1/voice-packs/{pack_id}/{version}/enable",
            "/api/v1/voice-packs/{pack_id}/{version}/select",
            "/api/v1/voice-packs/{pack_id}/{version}/disable",
            "/api/v1/voice-packs/{pack_id}/{version}",
        ],
        "target_namespace": "/api/v1/voice-packs",
        "migration_status": "modular",
        "data_owner": "voice_pack:ignored local registry+external or ignored runtime assets",
        "network_side_effects": "none for registry operations; selected pack is applied only to existing local TTS :9880",
        "failure_mode": "cross-site writes/preflight are rejected; validation/import is all-or-nothing; failed selection preserves the previous active pack when rollback succeeds; rollback failure reports no active pack and unknown engine state",
    },
    {
        "key": "voice_pack_distribution",
        "label": "Voice Pack 发布、远程获取与一键安装",
        "task_id": "PK-213",
        "task_file": "tasks/PK-213-voice-pack-distribution.md",
        "process": "project-tooling+main-api-contract",
        "current_endpoints": [
            "cli:voice-pack list|status|install|import|select|verify",
            "cli:voice-pack-build",
        ],
        "target_namespace": "/api/v1/voice-packs",
        "migration_status": "modular",
        "data_owner": "voice_pack_distribution:tracked trusted catalog plus ignored verified download cache; runtime assets and Registry remain owned by PK-212 and Engine remains owned by PK-211",
        "network_side_effects": "only explicit install may use the fixed HTTPS URL and per-hop host allowlist from a tracked catalog entry; current built-in catalog has no production release",
        "failure_mode": "exact confirmation, bounded redirects/body/archive, package SHA-256 before extraction, same-key idempotency only after PK-212 path-free content comparison, fail-closed link/hardlink/reparse build inputs and outside-source outputs, and no real Release until distribution rights and post-release PK-900 pass",
    },
)

_LIFECYCLE_SNAPSHOT_UNSET = object()


def _safe_lifecycle_state(module_id: str, state: Any) -> bool:
    if module_id in CORE_RESERVED_MODULE_IDS or not isinstance(state, dict):
        return False
    namespaces = state.get("api_namespaces", [])
    return isinstance(namespaces, list) and not any(
        isinstance(namespace, str) and conflicting_core_namespace(namespace)
        for namespace in namespaces
    )


def get_module_catalog(lifecycle_snapshot: Any = _LIFECYCLE_SNAPSHOT_UNSET) -> Dict[str, Any]:
    """Return static boundaries plus optional local-package lifecycle fields."""
    modules = deepcopy(list(_MODULES))
    try:
        managed = (
            get_module_manager().snapshot()
            if lifecycle_snapshot is _LIFECYCLE_SNAPSHOT_UNSET
            else deepcopy(lifecycle_snapshot)
        )
        if not isinstance(managed, dict):
            raise TypeError("module lifecycle snapshot must be a mapping")
        manager_error = None
    except Exception as exc:
        managed = {}
        manager_error = "%s: %s" % (type(exc).__name__, str(exc))

    known_keys = set()
    for item in modules:
        key = item["key"]
        contract = CORE_MODULE_CONTRACTS.get(key)
        known_keys.add(key)
        item.update({
            "managed": contract.managed if contract else False,
            "source": contract.source if contract else "legacy_builtin",
            "type": "sidecar" if key in {"qq_bridge", "gpt_sovits_engine_provider"} else "in_process",
            "required": contract.required if contract else False,
            "install_status": "enabled",
            "installed_version": None,
            "available_versions": [],
            "enabled": True,
            "configuration_ready": True,
            "dependencies": [],
            "optional_dependencies": [],
            "conflicts": [],
            "permissions": [],
            "requires_restart": False,
            "restart_required": False,
            "dashboard_entrypoint": None,
            "api_namespaces": (
                list(contract.api_namespaces)
                if contract else [item["target_namespace"]]
            ),
            "legacy_endpoints": list(item["current_endpoints"]),
            "previous_version": None,
            "last_operation": None,
            "data_policy": "preserve_on_uninstall",
            "available_actions": [],
            "package_source": None,
            "release": None,
        })
        if key == "focus":
            item.update({
                "managed": True,
                "source": "local_package",
                "install_status": "available",
                "enabled": False,
                "permissions": ["local_state"],
                "requires_restart": True,
                "api_namespaces": ["/api/v1/focus"],
                "legacy_endpoints": [
                    "/focus/status",
                    "/focus/start",
                    "/focus/stop",
                    "/focus/reset",
                ],
                "available_actions": ["install_official", "install_local"],
            })
        if key == "calendar":
            item.update({
                "permissions": ["local_state"],
                "api_namespaces": ["/api/v1/calendar"],
                "legacy_endpoints": [
                    "/calendar/today",
                    "/calendar/status",
                    "/calendar/event",
                    "/calendar/practice",
                    "/calendar/reset",
                ],
            })
        if key == "conversation":
            item.update({
                "api_namespaces": ["/api/v1/conversation", "/api/v1/llm-profile"],
                "legacy_endpoints": [
                    "/chat",
                    "/chat/text-only",
                    "/history",
                    "/history/clear",
                    "/ws/chat",
                    "/dashboard/llm/profile",
                ],
            })
        if key == "voice":
            item.update({
                "api_namespaces": ["/api/v1/voice", "/api/v1/voice-control"],
            })
        if key == "affection_memory":
            item.update({
                "permissions": ["local_state"],
                "api_namespaces": ["/api/v1/relationship", "/api/v1/memories"],
                "legacy_endpoints": [
                    "/affection/status",
                    "/affection/event",
                    "/affection/choose",
                    "/affection/reset",
                    "/memories",
                    "/memories/{memory_id}",
                    "/memories/clear",
                    "/chat",
                    "/chat/text-only",
                    "/ws/chat",
                ],
            })
        if contract is None and key in managed and _safe_lifecycle_state(key, managed[key]):
            item.update(managed[key])

    for key in sorted(set(managed) - known_keys - CORE_RESERVED_MODULE_IDS):
        state = managed[key]
        if not _safe_lifecycle_state(key, state):
            continue
        namespaces = state.get("api_namespaces") or ["/api/v1/%s" % key.replace("_", "-")]
        modules.append({
            "key": key,
            "label": state.get("name", key),
            "task_id": "LOCAL_%s" % key.upper(),
            "task_file": "",
            "process": "main-api" if state.get("type") == "in_process" else "sidecar",
            "current_endpoints": state.get("legacy_endpoints", []),
            "target_namespace": namespaces[0],
            "migration_status": "installable",
            **state,
        })
    return {
        "architecture": "modular-monolith",
        "catalog_version": 2,
        "module_manager_error": manager_error,
        "modules": modules,
    }
